/**
 *
 * @author Nicholas Allen, Daniel F Diaz Santiago
 */
package ECS.Main;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class AddEmployeeUI extends javax.swing.JFrame {

    public static HashMap<String, String> states_map = new HashMap<>();

    /**
     * Creates new form AddEmployeeUI
     */
    public AddEmployeeUI() {
        initComponents();
        populate_states_hashmap();
        notes_box.setLineWrap(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        skillset_list = new javax.swing.JList<>();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        notes_box = new javax.swing.JTextArea();
        address_box = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        city_box = new javax.swing.JTextField();
        zip_box = new javax.swing.JTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        state_dropdown = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        first_name_box = new javax.swing.JTextField();
        last_name_box = new javax.swing.JTextField();
        address_box2 = new javax.swing.JTextField();
        email_box = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        phone_box = new javax.swing.JTextField();
        javax.swing.JButton okay_btn = new javax.swing.JButton();
        javax.swing.JButton cancel_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jLabel2.setText("First Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("Address(Cont.):");

        jLabel5.setText("City:");

        jLabel7.setText("Phone #:");

        jLabel8.setText("Skillset:");

        skillset_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        skillset_list.setNextFocusableComponent(notes_box);
        jScrollPane1.setViewportView(skillset_list);

        jLabel11.setText("Notes:");

        notes_box.setColumns(20);
        notes_box.setRows(5);
        notes_box.setNextFocusableComponent(okay_btn);
        jScrollPane2.setViewportView(notes_box);

        address_box.setNextFocusableComponent(address_box2);

        jLabel10.setText("Email:");

        city_box.setNextFocusableComponent(state_dropdown);

        zip_box.setNextFocusableComponent(phone_box);
        zip_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zip_boxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zip_boxKeyTyped(evt);
            }
        });

        jLabel9.setText("State:");

        state_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));
        state_dropdown.setNextFocusableComponent(zip_box);

        jLabel6.setText("Zip:");

        first_name_box.setNextFocusableComponent(last_name_box);

        last_name_box.setNextFocusableComponent(address_box);

        address_box2.setNextFocusableComponent(city_box);

        email_box.setNextFocusableComponent(skillset_list);
        email_box.setPreferredSize(new java.awt.Dimension(312, 27));

        jLabel1.setText("Last Name:");

        phone_box.setNextFocusableComponent(email_box);
        phone_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_boxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_boxKeyTyped(evt);
            }
        });

        okay_btn.setText("Okay");
        okay_btn.setNextFocusableComponent(cancel_btn);
        okay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okay_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("Cancel");
        cancel_btn.setNextFocusableComponent(first_name_box);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(city_box, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(state_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zip_box, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(address_box2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(first_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(last_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phone_box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(email_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(okay_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancel_btn)))
                    .addComponent(address_box))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(last_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(address_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(zip_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phone_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(email_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okay_btn)
                    .addComponent(cancel_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void okay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okay_btnActionPerformed
        String state = states_map.get(state_dropdown.getSelectedItem().toString());

        if (validate_inputs()) {
            Employee newEmp = new Employee(first_name_box.getText(), last_name_box.getText(),
                    address_box.getText() + " " + address_box2.getText(), city_box.getText(),
                    state, zip_box.getText(), Long.parseLong(phone_box.getText()), email_box.getText(),
                    skillset_list.getSelectedValue(), "Good");
            Employee.addEmp(newEmp);
        }

        /*
        Employee(String _empFirstName, String _empLastName, String _empAddress, 
            String _empCity, String _empState, String _empZip, Long _empPhone, 
            String _empEmail, String _empSkills, String _empStatus)
         */
    }//GEN-LAST:event_okay_btnActionPerformed

    private void zip_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zip_boxKeyTyped
        // Allow only numbers
        char keys = evt.getKeyChar();

        if (!Character.isDigit(keys)) {
            evt.consume();
        }
    }//GEN-LAST:event_zip_boxKeyTyped

    private void phone_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_boxKeyTyped
        // Allow only numbers
        char keys = evt.getKeyChar();

        if (!Character.isDigit(keys)) {
            evt.consume();
        }
    }//GEN-LAST:event_phone_boxKeyTyped

    private void zip_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zip_boxKeyPressed
        // Limit input to 5
        if (zip_box.getText().length() >= 5) {
            // Allow backspace and delete
            if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
                zip_box.setEditable(true);
            } else {
                zip_box.setEditable(false);
            }
        } else {
            zip_box.setEditable(true);
        }
    }//GEN-LAST:event_zip_boxKeyPressed

    private void phone_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_boxKeyPressed
        // Limit input to 10
        if (phone_box.getText().length() >= 10) {
            // Allow backspace and delete
            if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getKeyCode() == KeyEvent.VK_DELETE) {
                phone_box.setEditable(true);
            } else {
                phone_box.setEditable(false);
            }
        } else {
            phone_box.setEditable(true);
        }
    }//GEN-LAST:event_phone_boxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void populate_states_hashmap() {
        states_map.put("Alabama", "AL");
        states_map.put("Alaska", "AK");
        states_map.put("Arizona", "AZ");
        states_map.put("Arkansas", "AR");
        states_map.put("California", "CA");
        states_map.put("Colorado", "CO");
        states_map.put("Connecticut", "CT");
        states_map.put("Delaware", "DE");
        states_map.put("Florida", "FL");
        states_map.put("Georgia", "GA");
        states_map.put("Hawaii", "HI");
        states_map.put("Idaho", "ID");
        states_map.put("Illinois", "IL");
        states_map.put("Indiana", "IN");
        states_map.put("Iowa", "IA");
        states_map.put("Kansas", "KS");
        states_map.put("Kentucky", "KY");
        states_map.put("Louisiana", "LA");
        states_map.put("Maine", "ME");
        states_map.put("Maryland", "MD");
        states_map.put("Massachusetts", "MA");
        states_map.put("Michigan", "MI");
        states_map.put("Minnesota", "MN");
        states_map.put("Mississippi", "MS");
        states_map.put("Missouri", "MO");
        states_map.put("Montana", "MT");
        states_map.put("Nebraska", "NE");
        states_map.put("Nevada", "NV");
        states_map.put("New Hampshire", "NH");
        states_map.put("New Jersey", "NJ");
        states_map.put("New Mexico", "NM");
        states_map.put("New York", "NY");
        states_map.put("North Carolina", "NC");
        states_map.put("North Dakota", "ND");
        states_map.put("Ohio", "OH");
        states_map.put("Oklahoma", "OK");
        states_map.put("Oregon", "OR");
        states_map.put("Pennsylvania", "PA");
        states_map.put("Rhode Island", "RI");
        states_map.put("South Carolina", "SC");
        states_map.put("South Dakota", "SD");
        states_map.put("Tennessee", "TN");
        states_map.put("Texas", "TX");
        states_map.put("Utah", "UT");
        states_map.put("Vermont", "VT");
        states_map.put("Virginia", "VA");
        states_map.put("Washington", "WA");
        states_map.put("West Virginia", "WV");
        states_map.put("Wisconsin", "WI");
        states_map.put("Wyoming", "WY");
    }

    private boolean validate_inputs() {
        // Validate first name
        if (first_name_box.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            first_name_box.requestFocus();
            return false;
        }

        // Validate last name
        if (last_name_box.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Last name is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            last_name_box.requestFocus();
            return false;
        }

        // Validate address
        if (address_box.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            address_box.requestFocus();
            return false;
        }

        // Validate city
        if (city_box.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "City is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            city_box.requestFocus();
            return false;
        }

        // Validate state
        String state = state_dropdown.getSelectedItem().toString();
        if (state.equals("Select")) {
            JOptionPane.showMessageDialog(this, "State is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            state_dropdown.requestFocus();
            return false;
        }

        // Validate ZIP code
        if (zip_box.getText().trim().isEmpty() || zip_box.getText().length() != 5) {
            JOptionPane.showMessageDialog(this, "Valid 5-digit ZIP code is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            zip_box.requestFocus();
            return false;
        }

        // Validate phone number
        String phone = phone_box.getText().trim();
        if (phone.isEmpty() || !phone.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Valid 10-digit phone number is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            phone_box.requestFocus();
            return false;
        }

        // Validate email
        String email = email_box.getText().trim();
        if (email.isEmpty() || !is_valid_email(email)) {
            JOptionPane.showMessageDialog(this, "Valid email is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            email_box.requestFocus();
            return false;
        }

        // Validate skillset
        if (skillset_list.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(this, "A skillset selection is required", "Input Error", JOptionPane.ERROR_MESSAGE);
            skillset_list.requestFocus();
            return false;
        }

        return true;
    }

    private boolean is_valid_email(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pat = Pattern.compile(emailRegex);
        return pat.matcher(email).matches();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField address_box;
    javax.swing.JTextField address_box2;
    javax.swing.JTextField city_box;
    javax.swing.JTextField email_box;
    javax.swing.JTextField first_name_box;
    javax.swing.JTextField last_name_box;
    javax.swing.JTextArea notes_box;
    javax.swing.JTextField phone_box;
    javax.swing.JList<String> skillset_list;
    javax.swing.JComboBox<String> state_dropdown;
    javax.swing.JTextField zip_box;
    // End of variables declaration//GEN-END:variables
}
