/**
 *
 * @author Nicholas Allen, Daniel F Diaz Santiago, Vaanitya Sangwan
 */
package ECS.Main;

import javax.swing.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;  // Unused because the line is commented out
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nicholas Allen
 */
public class MainUI extends javax.swing.JFrame {

        final String DB_URL = Settings.getJdbcUrl();
        final String DB_USER = Settings.getDbUsername();
        final String DB_PASSWORD = Settings.getDbPassword();
    
    /**
     * Creates new form Main
     */
    public MainUI() {
        initComponents();
        setLocationRelativeTo(null);
        populate_checkedout_table();
        populate_equipment_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JMenuItem jMenuItem7 = new javax.swing.JMenuItem();
        javax.swing.JFrame jFrame1 = new javax.swing.JFrame();
        javax.swing.ButtonGroup btnGrpSearch = new javax.swing.ButtonGroup();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel lblInUse4 = new javax.swing.JLabel();
        javax.swing.JSeparator jSeparator8 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JButton btnBeginCheckOut = new javax.swing.JButton();
        javax.swing.JButton btnBeginCheckIn = new javax.swing.JButton();
        javax.swing.JButton btnReportLost = new javax.swing.JButton();
        javax.swing.JButton btnReportFound = new javax.swing.JButton();
        javax.swing.JButton btnReportDamaged = new javax.swing.JButton();
        javax.swing.JLabel lblInUse5 = new javax.swing.JLabel();
        javax.swing.JSeparator jSeparator9 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
        javax.swing.JButton btnModifyEmp_MGMT = new javax.swing.JButton();
        javax.swing.JButton btnAddEmp_MGMT = new javax.swing.JButton();
        javax.swing.JButton btnOverrides_MGMT = new javax.swing.JButton();
        javax.swing.JButton btnAuthorization_MGMT = new javax.swing.JButton();
        javax.swing.JButton btnVerifyMGMT = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel lblInUse = new javax.swing.JLabel();
        scrCheckOutList = new javax.swing.JScrollPane();
        checkout_table = new javax.swing.JTable();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        scrCheckOutList1 = new javax.swing.JScrollPane();
        equipment_table = new javax.swing.JTable();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JLabel lblLoggedInUser = new javax.swing.JLabel();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator5 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem login_menu_item = new javax.swing.JMenuItem();
        javax.swing.JMenuItem logout_menu_item = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuCheckIn = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator6 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem mnuReportLost = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuReportDamaged = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator7 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem mnuReportFound = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenuItem mnuViewEmp = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem mnuAddEmp = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuModifyEmp = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator4 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.JMenu mnuAddEquip = new javax.swing.JMenu();
        javax.swing.JMenuItem mnuViewInv = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator10 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem muiOpenEquipUI = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuModifyEquipment = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuRemoveEquipment = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator11 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem mnuTransferEquipment = new javax.swing.JMenuItem();
        javax.swing.JMenuItem mnuPurchaseEquipment = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment Checkout System");

        lblInUse4.setText("Check-In/Check-Out");

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        btnBeginCheckOut.setText("Begin Check-Out");
        btnBeginCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginCheckOutActionPerformed(evt);
            }
        });

        btnBeginCheckIn.setText("Begin Check-In");
        btnBeginCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeginCheckInActionPerformed(evt);
            }
        });

        btnReportLost.setText("Report Lost Item");
        btnReportLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportLostActionPerformed(evt);
            }
        });

        btnReportFound.setText("Report Item Found");
        btnReportFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportFoundActionPerformed(evt);
            }
        });

        btnReportDamaged.setText("Report Damaged Item");
        btnReportDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDamagedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBeginCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBeginCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportLost, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportFound, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportDamaged, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnReportDamaged, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportFound, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportLost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeginCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeginCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInUse5.setText("Managment");

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel7.setEnabled(false);

        btnModifyEmp_MGMT.setText("Modify Employee");
        btnModifyEmp_MGMT.setMaximumSize(new java.awt.Dimension(146, 23));
        btnModifyEmp_MGMT.setMinimumSize(new java.awt.Dimension(146, 23));
        btnModifyEmp_MGMT.setPreferredSize(new java.awt.Dimension(146, 23));
        btnModifyEmp_MGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyEmp_MGMTActionPerformed(evt);
            }
        });

        btnAddEmp_MGMT.setText("Add Employee");
        btnAddEmp_MGMT.setMaximumSize(new java.awt.Dimension(146, 23));
        btnAddEmp_MGMT.setMinimumSize(new java.awt.Dimension(146, 23));
        btnAddEmp_MGMT.setPreferredSize(new java.awt.Dimension(146, 23));
        btnAddEmp_MGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmp_MGMTActionPerformed(evt);
            }
        });

        btnOverrides_MGMT.setText("Overrides");
        btnOverrides_MGMT.setMaximumSize(new java.awt.Dimension(146, 23));
        btnOverrides_MGMT.setMinimumSize(new java.awt.Dimension(146, 23));
        btnOverrides_MGMT.setPreferredSize(new java.awt.Dimension(146, 23));

        btnAuthorization_MGMT.setText("Authorization");
        btnAuthorization_MGMT.setMaximumSize(new java.awt.Dimension(146, 23));
        btnAuthorization_MGMT.setMinimumSize(new java.awt.Dimension(146, 23));
        btnAuthorization_MGMT.setPreferredSize(new java.awt.Dimension(146, 23));

        btnVerifyMGMT.setText("Verify MGMT");
        btnVerifyMGMT.setMaximumSize(new java.awt.Dimension(146, 23));
        btnVerifyMGMT.setMinimumSize(new java.awt.Dimension(146, 23));
        btnVerifyMGMT.setPreferredSize(new java.awt.Dimension(146, 23));
        btnVerifyMGMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyMGMTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerifyMGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddEmp_MGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifyEmp_MGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOverrides_MGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAuthorization_MGMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmp_MGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyEmp_MGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuthorization_MGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOverrides_MGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerifyMGMT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInUse.setText("Current Checked-Out List");

        scrCheckOutList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        checkout_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Transaction ID", "Equipment ID", "Equipment Name", "Equipment Description", "Check Out Date", "Due In Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        checkout_table.setShowGrid(false);
        checkout_table.setShowHorizontalLines(true);
        scrCheckOutList.setViewportView(checkout_table);

        scrCheckOutList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        equipment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Transaction ID", "Equipment ID", "Equipment Name", "Equipment Description", "Check Out Date", "Due In Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipment_table.setShowGrid(false);
        equipment_table.setShowHorizontalLines(true);
        scrCheckOutList1.setViewportView(equipment_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrCheckOutList)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInUse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addComponent(scrCheckOutList1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInUse)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrCheckOutList, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrCheckOutList1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrCheckOutList.getAccessibleContext().setAccessibleName("checkoutQueue");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblInUse4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblInUse5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInUse4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInUse5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        lblLoggedInUser.setText("Current User: ");
        lblLoggedInUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(lblLoggedInUser);

        jMenu1.setText("File");

        jMenuItem2.setText("Run Daily Reports");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator5);

        login_menu_item.setText("Login");
        login_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menu_itemActionPerformed(evt);
            }
        });
        jMenu1.add(login_menu_item);

        logout_menu_item.setText("Logout");
        logout_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menu_itemActionPerformed(evt);
            }
        });
        jMenu1.add(logout_menu_item);

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Check/Report");

        jMenuItem3.setText("Check-Out");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        mnuCheckIn.setText("Check-In");
        mnuCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCheckInActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCheckIn);
        jMenu2.add(jSeparator6);

        mnuReportLost.setText("Report Lost");
        mnuReportLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportLostActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReportLost);

        mnuReportDamaged.setText("Report Damaged");
        mnuReportDamaged.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportDamagedActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReportDamaged);
        jMenu2.add(jSeparator7);

        mnuReportFound.setText("Report Found");
        mnuReportFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportFoundActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReportFound);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Employee");

        mnuViewEmp.setText("View All Employees");
        mnuViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewEmpActionPerformed(evt);
            }
        });
        jMenu3.add(mnuViewEmp);
        jMenu3.add(jSeparator3);

        mnuAddEmp.setText("Add Employee");
        jMenu3.add(mnuAddEmp);

        mnuModifyEmp.setText("Modify Employee");
        jMenu3.add(mnuModifyEmp);
        jMenu3.add(jSeparator4);

        jMenuItem6.setText("Remove Employee");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        mnuAddEquip.setText("Equipment");

        mnuViewInv.setText("View Inventory");
        mnuAddEquip.add(mnuViewInv);
        mnuAddEquip.add(jSeparator10);

        muiOpenEquipUI.setText("Add Equipment");
        muiOpenEquipUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muiOpenEquipUIActionPerformed(evt);
            }
        });
        mnuAddEquip.add(muiOpenEquipUI);

        mnuModifyEquipment.setText("Modify Equipment");
        mnuAddEquip.add(mnuModifyEquipment);

        mnuRemoveEquipment.setText("Remove Equipment");
        mnuRemoveEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveEquipmentActionPerformed(evt);
            }
        });
        mnuAddEquip.add(mnuRemoveEquipment);
        mnuAddEquip.add(jSeparator11);

        mnuTransferEquipment.setText("Transfer Equipment");
        mnuAddEquip.add(mnuTransferEquipment);

        mnuPurchaseEquipment.setText("Purchase Equipment");
        mnuAddEquip.add(mnuPurchaseEquipment);

        jMenuBar1.add(mnuAddEquip);

        jMenu4.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Settings");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuReportFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportFoundActionPerformed
        ReportFoundUI newFrame = new ReportFoundUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuReportFoundActionPerformed

    private void btnBeginCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginCheckOutActionPerformed
        CheckOutUI checkOutFrame = new CheckOutUI();  // Create a new instance of CheckOutUI
        checkOutFrame.setVisible(true);  // Make the CheckOutUI visible
        checkOutFrame.setLocationRelativeTo(null);  // Center the CheckOutUI on the screen
    }//GEN-LAST:event_btnBeginCheckOutActionPerformed

    private void btnBeginCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeginCheckInActionPerformed
        CheckInUI checkInFrame = new CheckInUI();
        checkInFrame.setVisible(true);
        checkInFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBeginCheckInActionPerformed

    private void btnReportDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDamagedActionPerformed
        ReportDamagedUI newFrame = new ReportDamagedUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportDamagedActionPerformed

    private void btnModifyEmp_MGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyEmp_MGMTActionPerformed
        ModifyEmployeeUI newFrame = new ModifyEmployeeUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnModifyEmp_MGMTActionPerformed

    private void btnAddEmp_MGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmp_MGMTActionPerformed
        AddEmployeeUI newFrame = new AddEmployeeUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddEmp_MGMTActionPerformed

    private void btnVerifyMGMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyMGMTActionPerformed
        VerifyManagementUI newFrame = new VerifyManagementUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnVerifyMGMTActionPerformed

    private void btnReportFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportFoundActionPerformed
        ReportFoundUI newFrame = new ReportFoundUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnReportFoundActionPerformed

    private void mnuViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewEmpActionPerformed
        ViewEmployeeUI newFrame = new ViewEmployeeUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuViewEmpActionPerformed

    private void muiOpenEquipUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muiOpenEquipUIActionPerformed
        AddEquipmentUI equipmentUI = new AddEquipmentUI();
        equipmentUI.setVisible(true);
        equipmentUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_muiOpenEquipUIActionPerformed

    private void login_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menu_itemActionPerformed
        LoginUI login_ui = new LoginUI();
        login_ui.setVisible(true);
    }//GEN-LAST:event_login_menu_itemActionPerformed

    private void logout_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menu_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_menu_itemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CheckOutUI checkOutFrame = new CheckOutUI();  // Create a new instance of CheckOutUI
        checkOutFrame.setVisible(true);  // Make the CheckOutUI visible
        checkOutFrame.setLocationRelativeTo(null);  // Center the CheckOutUI on the screen
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCheckInActionPerformed
        CheckInUI checkInFrame = new CheckInUI();
        checkInFrame.setVisible(true);
        checkInFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuCheckInActionPerformed

    private void btnReportLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportLostActionPerformed
        ReportLostUI reportLostFrame = new ReportLostUI();
        reportLostFrame.setVisible(true);
        reportLostFrame.setLocationRelativeTo(null);    }//GEN-LAST:event_btnReportLostActionPerformed

    private void mnuReportLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportLostActionPerformed
        ReportLostUI reportLostFrame = new ReportLostUI();
        reportLostFrame.setVisible(true);
        reportLostFrame.setLocationRelativeTo(null);    }//GEN-LAST:event_mnuReportLostActionPerformed

    private void mnuReportDamagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportDamagedActionPerformed
        ReportDamagedUI newFrame = new ReportDamagedUI();
        newFrame.setVisible(true);
        newFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuReportDamagedActionPerformed

    private void mnuRemoveEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveEquipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRemoveEquipmentActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AboutUI aboutFrame = new AboutUI();
        aboutFrame.setVisible(true);
        aboutFrame.setLocationRelativeTo(null);    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SettingsUI settingsFrame = new SettingsUI();
        settingsFrame.setVisible(true);
        settingsFrame.setLocationRelativeTo(null);    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
private void populate_equipment_table() {
        System.out.println("Connecting to Database to populate Inventory...");


        

        // Hashmap for equipment descriptions, NEEDS TO BE UPDATED
        // Fill this.
        
        HashMap<Integer, String> equipment_descriptions = new HashMap<>();
        equipment_descriptions.put(1, "DESCRIPTION 1");
        equipment_descriptions.put(2, "DESCRIPTION 2");
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Establish connection
            conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            System.out.println("Connection Succeeded...");
            // Fetch checkout and employee details
            String sql = "SELECT e.itemID, e.itemName, e.itemQuantity, e.itemAvailability, e.numOut, e.itemPrice, e.isConsumable, e.SkillRequired "
                    + "FROM CEIS400_group_project.Equipment e ";
            pstmt = conn.prepareStatement(sql);

            // Execute query
            rs = pstmt.executeQuery();

            // Get the table model
            DefaultTableModel tableModel = (DefaultTableModel) equipment_table.getModel();

            // Clear existing rows in the table
            tableModel.setRowCount(0);
            
            // Process results and add to table model
            while (rs.next()) {
                System.out.println("Compiling data...");
                int item_id = rs.getInt("itemID");
                String item_name = rs.getString("itemName");
                int item_quantity = rs.getInt("itemQuantity");
                int item_availability = rs.getInt("itemAvailability");
                int num_out = rs.getInt("numOut");
                int item_price = rs.getInt("itemPrice");
                int is_consumable = rs.getInt("isConsumable");
                String skill_required = rs.getString("SkillRequired");
                String equipment_description = equipment_descriptions.getOrDefault(item_id, "Unknown");

                tableModel.addRow(new Object[]{item_id, item_name, equipment_description, item_quantity, item_availability, 
                    num_out, item_price, is_consumable, skill_required});
                System.out.println("Adding Row Succeeded...");                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            // Commented this out because my DB is empty. It keeps showing this error every time I run it.
            //JOptionPane.showMessageDialog(this, "Error fetching check-out data.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
                System.out.println("Database Connection Closed...");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    private void populate_checkedout_table() {


        // Hashmap for equipment descriptions, NEEDS TO BE UPDATED
        // Fill this.
        HashMap<Integer, String> equipment_descriptions = new HashMap<>();
        equipment_descriptions.put(1, "DESCRIPTION 1");
        equipment_descriptions.put(2, "DESCRIPTION 2");

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Establish connection
            conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);

            // Fetch checkout and employee details
            String sql = "SELECT c.TransactionID, c.empID, e.FirstName, e.LastName, c.EquipmentID, c.CheckoutDate, c.ReturnDate "
                    + "FROM CEIS400_group_project.Checkout c "
                    + "JOIN CEIS400_group_project.Employee e ON c.empID = e.empID";
            pstmt = conn.prepareStatement(sql);

            // Execute query
            rs = pstmt.executeQuery();

            // Get the table model
            DefaultTableModel tableModel = (DefaultTableModel) checkout_table.getModel();

            // Clear existing rows in the table
            tableModel.setRowCount(0);

            // Process results and add to table model
            while (rs.next()) {
                int transaction_id = rs.getInt("TransactionID");
                int emp_id = rs.getInt("empID");
                String first_name = rs.getString("FirstName");
                String last_name = rs.getString("LastName");
                int equipment_id = rs.getInt("EquipmentID");
                String checkout_date = rs.getDate("CheckoutDate").toString();
                String return_date = rs.getDate("ReturnDate") != null ? rs.getDate("ReturnDate").toString() : "";
                String equipment_name = "Equipment " + equipment_id; // Placeholder for actual equipment name
                String equipment_description = equipment_descriptions.getOrDefault(equipment_id, "Unknown");

                tableModel.addRow(new Object[]{emp_id, first_name + " " + last_name, transaction_id, equipment_id, 
                    equipment_name, equipment_description, checkout_date, return_date});
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            // Commented this out because my DB is empty. It keeps showing this error every time I run it.
            //JOptionPane.showMessageDialog(this, "Error fetching check-out data.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    private javax.swing.JTextArea txaViewInv;
    public String loggedInUser = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTable checkout_table;
    javax.swing.JTable equipment_table;
    javax.swing.JScrollPane scrCheckOutList;
    javax.swing.JScrollPane scrCheckOutList1;
    // End of variables declaration//GEN-END:variables

}
